#!/usr/bin/env python3
"""ADR-0037 exact CAP-SYNTH and owner-source ENT-STRAT evaluation runtime."""
from __future__ import annotations
import copy, uuid
from typing import Any
from accepted_live_enterprise_arch_runtime import build_gate, load_exact_input
from artifact_ledger import content_hash
from enterprise_arch_runtime import BASELINE, rehash
from validate_vertical_slice import ROOT, ValidationFailure, assert_schema, load_json

AUTHORITY=ROOT/"appendices/governance/snapshots/decision-authorities-0.9.0.json"
REPORT=ROOT/"fixtures/vertical-risk-slice/evidence/governance-increment3-report-reconciliation-2026-07-31/reference-run/report-package.json"
NS=uuid.UUID("37000000-0000-4000-8000-000000000000"); NOW="2026-08-02T12:00:00Z"
OWNED=["objective_and_method_authority","manifest_bindings","objective_scorecards","normalization_method","weighting_model","confidence_distributions","sensitivity_analysis","missing_data_effects","threshold_context","strategic_confidence_posture","composite_score","authority_boundary"]

def sid(*p:str)->str:return str(uuid.uuid5(NS,"|".join(p)))
def hashed(v:dict[str,Any],f:str)->dict[str,Any]:
 m=copy.deepcopy(v);m[f]=None;v[f]=content_hash(m);return v
def pointer(v:Any,p:str)->Any:
 for token in p.lstrip("/").split("/"):v=v[int(token)] if isinstance(v,list) else v[token.replace("~1","/").replace("~0","~")]
 return v
def authority_declaration()->dict[str,Any]:
 r=load_json(AUTHORITY);o=next(x for x in r["authorities"] if x["authority_role"]=="project-owner")
 needed={"declare_project_strategic_evaluation_objectives","declare_project_strategic_scoring_method"}
 if r["registry_version"]!="0.9.0" or "CODE-HARNESS-PROJECT-001" not in o["scope_ids"] or "HUMAN-PROJECT-OWNER-001" not in o["human_subject_ids"] or not needed<=set(o["allowed_actions"]):raise ValidationFailure("ADR-0037 corrected project strategy authority is absent")
 return {"authority_role":"project-owner","authority_name":"thomasverburgt","subject_id":"HUMAN-PROJECT-OWNER-001","authority_registry":{"registry_id":r["registry_id"],"registry_version":r["registry_version"],"registry_hash":content_hash(r)}}
def build_sources()->tuple[dict[str,Any],dict[str,Any]]:
 d=authority_declaration();obj={"manifest_id":sid("objectives","0.9.0"),"manifest_version":"1.0.0","created_at":NOW,"scope_id":"CODE-HARNESS-PROJECT-001","declared_by":d,"objectives":[{"objective_id":"STRAT-HARNESS-DECISION-QUALITY-001","outcome":"Preserve traceable, human-controlled Code Harness review outputs for leadership and expert decisions.","owner":"project-owner","applicability":"applicable","measures":[{"measure_id":"MEASURE-HUMAN-AUTHORITY","description":"The capability posture preserves human decision authority and advisory-only agent operation.","direction":"higher_is_better"},{"measure_id":"MEASURE-FINDING-LOCATOR-COVERAGE","description":"Findings expose exact source-file and location context sufficient for human correctness review.","direction":"higher_is_better"}]}],"manifest_hash":"sha256:"+"0"*64};hashed(obj,"manifest_hash")
 method={"method_id":sid("method","0.9.0"),"method_version":"1.0.0","created_at":NOW,"scope_id":"CODE-HARNESS-PROJECT-001","declared_by":d,"normalization":"identity_0_1","weights":{"MEASURE-HUMAN-AUTHORITY":0.5,"MEASURE-FINDING-LOCATOR-COVERAGE":0.5},"aggregation":"weighted_mean","missingness":"preserve_unknown_no_imputation","confidence":"confidence_in_bounded_evidence_insufficiency_not_strategic_approval","measure_mappings":{"MEASURE-HUMAN-AUTHORITY":{"mapping_rule_id":"MAP-HUMAN-AUTHORITY-001","source_locator_ids":["STRAT-EVID-HUMAN-AUTHORITY","STRAT-EVID-ADVISORY-ONLY"],"evaluation_rule":"all_expected_values_match","normalized_value_if_true":1.0,"normalized_value_if_false":0.0},"MEASURE-FINDING-LOCATOR-COVERAGE":{"mapping_rule_id":"MAP-FINDING-LOCATOR-COVERAGE-001","evaluation_rule":"ratio_of_findings_with_resolvable_file_and_location","missing_when_no_report_finding_records_are_admitted":True}},"confidence_derivation":{"evidence_coverage":"observed_measure_count_divided_by_eligible_measure_count","component_confidence":"preserve_source_assessment_confidence","assessment_confidence":"minimum_observed_source_confidence","reconciliation":"confidence_applies_to_bounded_insufficiency_not_strategic_approval"},"sensitivity":{"weight_delta":0.1},"composite_allowed":False,"threshold_context":None,"method_hash":"sha256:"+"0"*64};hashed(method,"method_hash")
 validate_sources(obj,method);return obj,method
def validate_sources(obj:dict[str,Any],method:dict[str,Any])->None:
 assert_schema(obj,"strategic-objective-manifest.schema.json","ADR-0037 objectives");assert_schema(method,"strategic-scoring-method-manifest.schema.json","ADR-0037 method")
 for v,f in ((obj,"manifest_hash"),(method,"method_hash")):
  m=copy.deepcopy(v);h=m[f];m[f]=None
  if content_hash(m)!=h:raise ValidationFailure("ADR-0037 source hash mismatch")
 if obj["declared_by"]!=authority_declaration() or method["declared_by"]!=authority_declaration():raise ValidationFailure("ADR-0037 source authority mismatch")
 expected_measures={m["measure_id"] for o in obj["objectives"] for m in o["measures"]}
 if obj["scope_id"]!="CODE-HARNESS-PROJECT-001" or obj["scope_id"]!=method["scope_id"] or set(method["weights"])!=expected_measures or set(method["measure_mappings"])!=expected_measures or abs(sum(method["weights"].values())-1)>1e-9:raise ValidationFailure("ADR-0037 corrected method coverage or scope mismatch")
 mapping=method["measure_mappings"]["MEASURE-HUMAN-AUTHORITY"]
 if mapping!={"mapping_rule_id":"MAP-HUMAN-AUTHORITY-001","source_locator_ids":["STRAT-EVID-HUMAN-AUTHORITY","STRAT-EVID-ADVISORY-ONLY"],"evaluation_rule":"all_expected_values_match","normalized_value_if_true":1.0,"normalized_value_if_false":0.0}:raise ValidationFailure("ADR-0037 categorical mapping is not exact")
def build_evidence(cap:dict[str,Any])->dict[str,Any]:
 refs=[("STRAT-EVID-HUMAN-AUTHORITY","/decision_authority","human"),("STRAT-EVID-ADVISORY-ONLY","/extensions/capability/role/capability_posture/advisory_only",True)]
 v={"manifest_id":sid("evidence",cap["artifact"]["artifact_id"]),"manifest_version":"1.0.0","created_at":NOW,"bindings":[{"locator_id":i,"measure_id":"MEASURE-HUMAN-AUTHORITY","source_artifact_id":cap["artifact"]["artifact_id"],"source_artifact_hash":cap["integrity"]["output_hash"],"json_pointer":p,"expected_value":e,"purpose":"Exact evidence for the human-authority measure."} for i,p,e in refs],"manifest_hash":"sha256:"+"0"*64};hashed(v,"manifest_hash");validate_evidence(v,cap);return v
def validate_evidence(v:dict[str,Any],cap:dict[str,Any])->None:
 assert_schema(v,"enterprise-strategy-evidence-binding.schema.json","ADR-0037 evidence")
 m=copy.deepcopy(v);h=m["manifest_hash"];m["manifest_hash"]=None
 if content_hash(m)!=h or any(b["source_artifact_hash"]!=cap["integrity"]["output_hash"] or pointer(cap,b["json_pointer"])!=b["expected_value"] for b in v["bindings"]):raise ValidationFailure("ADR-0037 evidence binding mismatch")
def build_input(cap:dict[str,Any],elig:dict[str,Any],obj:dict[str,Any],method:dict[str,Any],evidence:dict[str,Any])->tuple[dict[str,Any],dict[str,Any]]:
 gate=build_gate(cap);v={"manifest_id":sid("input",cap["artifact"]["artifact_id"],obj["manifest_hash"],method["method_hash"]),"manifest_version":"1.0.0","created_at":NOW,"gate":{"id":gate["artifact"]["artifact_id"],"hash":content_hash(gate)},"cap_synth":{"id":cap["artifact"]["artifact_id"],"hash":cap["integrity"]["output_hash"]},"cap_synth_eligibility":{"id":elig["eligibility_id"],"hash":elig["record_hash"]},"objective_manifest":{"id":obj["manifest_id"],"hash":content_hash(obj)},"scoring_method":{"id":method["method_id"],"hash":content_hash(method)},"evidence_manifest":{"id":evidence["manifest_id"],"hash":content_hash(evidence)},"excluded_child_artifact_ids":sorted(cap["artifact"]["links"]["children"]),"input_hash":"sha256:"+"0"*64};hashed(v,"input_hash");assert_schema(v,"enterprise-strategy-evaluation-input.schema.json","ADR-0037 input");return gate,v
def role(gate,cap,elig,obj,method,evidence,inp):
 observed={"measure_id":"MEASURE-HUMAN-AUTHORITY","direction":"higher_is_better","weight":0.5,"mapping_rule_id":"MAP-HUMAN-AUTHORITY-001","normalized_value":1.0,"evidence_refs":[x["locator_id"] for x in evidence["bindings"]],"source_artifact_ids":[cap["artifact"]["artifact_id"]],"source_evidence_tier":"accepted_live_multi_domain_capability_synthesis_evaluation","confidence":0.85,"confidence_derivation":"preserve_source_assessment_confidence","state":"observed"}
 missing={"measure_id":"MEASURE-FINDING-LOCATOR-COVERAGE","direction":"higher_is_better","weight":0.5,"normalized_value":None,"evidence_refs":[],"source_artifact_ids":[],"source_evidence_tier":"unavailable","confidence":None,"state":"missing"}
 bind={"gate_artifact_id":gate["artifact"]["artifact_id"],"gate_artifact_hash":content_hash(gate),"posture_artifact_ids":[cap["artifact"]["artifact_id"]],"posture_artifact_hashes":[cap["integrity"]["output_hash"]],"cap_synth_eligibility_id":elig["eligibility_id"],"cap_synth_eligibility_hash":elig["record_hash"],"objective_manifest_id":obj["manifest_id"],"objective_manifest_hash":content_hash(obj),"scoring_method_id":method["method_id"],"scoring_method_hash":content_hash(method),"evidence_manifest_id":evidence["manifest_id"],"evidence_manifest_hash":content_hash(evidence),"evaluation_input_manifest_id":inp["manifest_id"],"evaluation_input_manifest_hash":inp["input_hash"],"binding_state":"exact"}
 return {"designation":"ENT-STRAT","evidence_tier":"accepted_live_multi_domain_single_capability_strategy_evaluation","fitness_claim":"single_capability_project_strategy_evaluation","manifest_binding":bind,"input_evidence_tiers":[{"artifact_id":cap["artifact"]["artifact_id"],"designation":"CAP-SYNTH","evidence_tier":"accepted_live_multi_domain_capability_synthesis_evaluation"}],"objective_scorecards":[{"objective_id":obj["objectives"][0]["objective_id"],"outcome":obj["objectives"][0]["outcome"],"components":[observed,missing],"state":"insufficient_evidence","composite_score":None}],"normalization_method":"identity_0_1","weighting_model":method["weights"],"confidence_distributions":[{"objective_id":obj["objectives"][0]["objective_id"],"basis":"observed_components_only_not_objective_completeness","observed_components":1,"eligible_components":2,"component_min":1.0,"component_max":1.0,"composite":None,"false_precision_avoided":True}],"sensitivity_analysis":[{"objective_id":obj["objectives"][0]["objective_id"],"authorized_weight_delta":0.1,"result":"not_calculated_composite_prohibited"}],"missing_data_effects":[{"objective_id":obj["objectives"][0]["objective_id"],"measure_id":"MEASURE-FINDING-LOCATOR-COVERAGE","effect":"Strategic alignment remains insufficient_evidence; no value is imputed and no composite is calculated."}],"disagreement_register":[],"threshold_context":None,"strategic_confidence_posture":{"state":"insufficient_evidence","advisory_only":True,"evidence_coverage":0.5,"assessment_confidence":0.85,"confidence_derivation":method["confidence_derivation"],"rationale":"Human authority is evidenced under declared mapping MAP-HUMAN-AUTHORITY-001, but exact finding-locator coverage is not established by the bounded CAP-SYNTH artifact."},"composite_score":None,"decision_requests":[],"unsupported_claims":[],"downstream_handoff":{"consumers":["ENT-SYNTH-CANDIDATE","ENT-PORTFOLIO-CANDIDATE"],"handoff_state":"comparison_only","scheduled":False},"decision_authority":"human"}
def build_candidate(raw_hash:str|None=None)->dict[str,Any]:
 cap,elig=load_exact_input();obj,method=build_sources();evidence=build_evidence(cap);gate,inp=build_input(cap,elig,obj,method,evidence);r=role(gate,cap,elig,obj,method,evidence,inp);aid=sid("candidate",inp["manifest_id"])
 mode="model_response_with_harness_owned_strategy_projection" if raw_hash else "deterministic_reference_projection"
 if raw_hash is not None and (len(raw_hash)!=64 or any(ch not in "0123456789abcdef" for ch in raw_hash)):raise ValidationFailure("raw response hash is invalid")
 capability_id=cap["extensions"]["capability"]["capability_id"]
 c={"identity":{"agent_uuid":"0275dcd7-ef2d-4535-8b3b-0e6da66ebff6","designation":"ENT-STRAT","display_name":"Strategic Scoring Agent","agent_version":"design-0.1.0","contract_version":"1.0.0"},
    "artifact":{"artifact_id":aid,"artifact_type":"enterprise-strategic-confidence","created_at":NOW,"lifecycle_state":"complete","links":{"parents":[],"children":[gate["artifact"]["artifact_id"],cap["artifact"]["artifact_id"]],"peers":[]}},
    "execution":{"execution_id":sid(aid,"execution",mode),"model":"qwen3-32b" if raw_hash else "deterministic-reference-agent","prompt_version":"design-0.1.0","rubric_version":"0.1.0","toolchain_version":"0.1.0","generation_mode":mode,"raw_model_response_sha256":raw_hash,"harness_owned_fields":OWNED,"settings":{"temperature":0}},
    "scope":{"enterprise_scope_id":obj["scope_id"],"participating_capabilities":[capability_id],"assessment_period":"2026-08-02","decision_context":"accepted_live_single_capability_strategy_evaluation"},
    "inputs":[{"artifact_id":cap["artifact"]["artifact_id"],"hash":cap["integrity"]["output_hash"],"compatibility":"compatible","freshness":"fresh"},{"reference":"enterprise-strategy-input-manifest","hash":inp["input_hash"],"compatibility":"compatible","freshness":"fresh"}],
    "methodology":{"method":"owner-source and eligibility gated project strategy evaluation","limitations":["One capability only","No enterprise strategy or investment approval","Comparison only","All strategy fields are deterministic harness projections; raw model output is retained separately."]},
    "coverage":{"eligible":2,"reviewed":1,"omitted":0,"inaccessible":0,"unknown":1,"negative_evidence":0},"observations":[],"assessments":[],"findings":[],"patterns":[],"insights":[],"conflicts":[],
    "confidence":{"evidence":0.5,"assessment":0.85,"review":1.0,"decision":None,"provenance":[{"artifact_id":cap["artifact"]["artifact_id"],"confidence":0.85}]},"decisions_requested":[],"consumers":r["downstream_handoff"]["consumers"],"decision_authority":"human",
    "integrity":{"input_hash":inp["input_hash"],"output_hash":None,"attestation_ref":None,"retention_class":"candidate-test","schema_validation":"passed"},
    "extensions":{"enterprise":{"enterprise_scope":{"enterprise_scope_id":obj["scope_id"],"assessment_period":"2026-08-02"},"participating_capabilities":[capability_id],"capability_input_manifest":[{"artifact_id":cap["artifact"]["artifact_id"],"content_hash":cap["integrity"]["output_hash"],"state":"valid"}],"cross_capability_correlations":[],"enterprise_assertions":r["objective_scorecards"],"systemic_dependencies":[],"enterprise_unknowns":r["missing_data_effects"],"unresolved_disagreements":[],"confidence_reconciliation":{"method":method["confidence_derivation"],"result":{"evidence_coverage":0.5,"assessment_confidence":0.85}},"human_decision_requests":[],"enterprise_traceability_manifest":r["manifest_binding"],"role":r}}}
 rehash(c);validate_candidate(c,gate,cap,elig,obj,method,evidence,inp);return c
def validate_candidate(c,gate,cap,elig,obj,method,evidence,inp):
 assert_schema(c,"universal-agent-artifact.schema.json","ADR-0037 candidate");assert_schema(c["extensions"]["enterprise"],"enterprise-extension.schema.json","ADR-0037 enterprise");assert_schema(c["extensions"]["enterprise"]["role"],"ent-strat-role.schema.json","ADR-0037 role");m=copy.deepcopy(c);h=m["integrity"]["output_hash"];m["integrity"]["output_hash"]=None
 if content_hash(m)!=h or c["extensions"]["enterprise"]["role"]!=role(gate,cap,elig,obj,method,evidence,inp):raise ValidationFailure("ADR-0037 candidate mismatch")
 if any(n["designation"]=="ENT-STRAT" for n in load_json(BASELINE)["nodes"]):raise ValidationFailure("ENT-STRAT is scheduled")
def build_packet(c,inp):
 v={"packet_id":sid("review",c["artifact"]["artifact_id"]),"packet_version":"1.0.0","generated_at":NOW,"candidate":{"id":c["artifact"]["artifact_id"],"hash":c["integrity"]["output_hash"]},"input_manifest":{"id":inp["manifest_id"],"hash":inp["input_hash"]},"projection_provenance":{"generation_mode":c["execution"]["generation_mode"],"raw_model_response_sha256":c["execution"]["raw_model_response_sha256"],"harness_owned_fields":OWNED},"review_dimensions":["source_authority","objective_preservation","method_preservation","capability_evidence","missingness","confidence_and_uncertainty","authority_boundary","rollback"],"review_state":"awaiting_human_semantic_review","required_authority":"project-owner","effect":"review_request_only","cap_synth_scheduled":False,"ent_strat_scheduled":False,"report_effect":"none","deployment_effect":"none","packet_hash":"sha256:"+"0"*64};hashed(v,"packet_hash");assert_schema(v,"enterprise-strategy-semantic-review-packet.schema.json","ADR-0037 packet");return v
def build_package(raw_hash:str|None=None):
 cap,elig=load_exact_input();obj,method=build_sources();evidence=build_evidence(cap);gate,inp=build_input(cap,elig,obj,method,evidence);c=build_candidate(raw_hash);return cap,elig,obj,method,evidence,gate,inp,c,build_packet(c,inp)
