#!/usr/bin/env python3
"""Generate controlled ADR-0039 Increment 5-7 specialist files deterministically."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
from artifact_ledger import atomic_write, pretty_bytes
from validate_vertical_slice import ROOT, load_json

ROLES={
"SPEC-ARCH":("spec-arch","Architecture Reviewer","Does implementation conform to declared architecture without conflating intended and observed state?","architecture_assessment_only_no_product_or_release_approval",5),
"SPEC-INTEROP":("spec-interop","Interoperability and Integration Reviewer","Are interfaces and integrations compatible, traceable, and failure-aware?","interface_assessment_only_no_product_or_release_approval",5),
"SPEC-DATA":("spec-data","Data Architecture and Information Management Reviewer","Are information semantics, ownership, lineage, and lifecycle controls explicit?","data_assessment_only_no_governance_or_product_approval",5),
"SPEC-DIAGRAM":("spec-diagram","Diagram and Design-Model Reviewer","Do admitted models faithfully represent declared structure without being treated as runtime truth?","design_model_assessment_only_no_implementation_or_product_approval",5),
"SPEC-IO":("spec-io","I/O and Resource Interaction Reviewer","Are external resource interactions, permissions, failure modes, and ownership explicit?","resource_interaction_assessment_only_no_runtime_or_product_approval",5),
"SPEC-OBS":("spec-obs","Observability Reviewer","Can admitted telemetry design diagnose declared behaviors and failures?","observability_assessment_only_no_operational_or_product_approval",6),
"SPEC-PERF":("spec-perf","Performance and Scalability Reviewer","What performance claims are supported by admitted workload and measurement evidence?","performance_assessment_only_no_capacity_or_product_approval",6),
"SPEC-FMECA":("spec-fmeca","Reliability, Resilience, and FMECA Reviewer","What failure modes, propagation, controls, recovery, and mission effects are evidenced?","reliability_assessment_only_no_resilience_or_product_approval",6),
"SPEC-RESEARCH":("spec-research","Research and Product-Store Agent","Are admitted sources attributable, content-addressed, licensed, current enough, and relevant?","research_evidence_only_no_authority_or_product_approval",7),
"SPEC-RISK":("spec-risk","Product Risk Reviewer","What bounded cause-event-consequence risks follow from retained specialist evidence?","risk_characterization_only_no_acceptance_or_product_approval",7),
"SPEC-SECURITY":("spec-security","Security Posture Reviewer","What bounded security posture follows while preserving child disagreement and missingness?","security_synthesis_only_no_whole_product_release_or_acceptance",7),
}
SEED={"SPEC-DIAGRAM","SPEC-IO","SPEC-RESEARCH","SPEC-RISK","SPEC-SECURITY"}
MODEL={"manifest_version":"0.1.0","provider":"vllm-openai-compatible","model_id":"qwen3-32b","upstream_model":"Qwen/Qwen3-32B-FP8","upstream_revision":"aa55da1ecc13d006e8b8e4f54579b1ea8c3db2df","container_image":"nvcr.io/nvidia/vllm:26.06-py3@sha256:63b808804826a028e38f559747a9e4d5985cf676616fbaa70c1937c58f83e13e","temperature":0,"thinking_mode":"disabled","max_output_tokens":4096,"structured_output":"strict role schema","credential_policy":"environment-injected; never persisted","scheduled":False,"product_fan_in_eligible":False,"a100_production_authorized":False}
def schema(designation,boundary):
 return {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":f"https://code-review-harness/schemas/{ROLES[designation][0]}-role.schema.json","title":f"{designation} Candidate Role Extension","type":"object","additionalProperties":False,"required":["designation","domain_records","coverage","unknowns","authority_boundary"],"properties":{"designation":{"const":designation},"domain_records":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":False,"required":["record_id","subject","assessment_state","evidence_tier","effectiveness","evidence_refs"],"properties":{"record_id":{"type":"string","minLength":1},"subject":{"type":"string","minLength":1},"assessment_state":{"enum":["observed_positive_control","bounded_concern","insufficient_evidence"]},"evidence_tier":{"enum":["configuration","design_model","source_contract","test","runtime","external_source","retained_candidate"]},"effectiveness":{"enum":["demonstrated","configured_not_demonstrated","not_assessed"]},"evidence_refs":{"type":"array","minItems":1,"uniqueItems":True,"items":{"type":"string"}}}}},"coverage":{"type":"object","additionalProperties":False,"required":["records_reviewed","tests_reviewed","runtime_records_reviewed","external_sources_reviewed"],"properties":{"records_reviewed":{"type":"integer","minimum":0},"tests_reviewed":{"type":"integer","minimum":0},"runtime_records_reviewed":{"type":"integer","minimum":0},"external_sources_reviewed":{"type":"integer","minimum":0}}},"unknowns":{"type":"array","minItems":1,"items":{"type":"object","additionalProperties":False,"required":["unknown_id","statement","missing_evidence","evidence_refs"],"properties":{"unknown_id":{"type":"string"},"statement":{"type":"string"},"missing_evidence":{"type":"array","minItems":1,"items":{"type":"string"}},"evidence_refs":{"type":"array","minItems":1,"items":{"type":"string"}}}}},"authority_boundary":{"const":boundary}}}
def main():
 manifest=load_json(ROOT/"appendices/prompt-templates/candidates/manifest.json")
 for designation,(slug,display,question,boundary,inc) in ROLES.items():
  prompt=(f"BEGIN {designation} PROMPT\nYou are {designation}, the {display}. Operate only as an ADR-0039 Increment {inc} comparison-only specialist under the exact registry identity, universal and specialist contracts, focus profile, dispatch, schema, rubric, model, and tool bindings. Authoritative question: {question} Inspect only admitted evidence and cite exact evidence IDs. Preserve intended, implemented, configured, tested, observed, and desired states; do not turn missing evidence into effective controls. Static configuration, design models, retained candidates, or external descriptions cannot demonstrate runtime effectiveness. Preserve original record identifiers, disagreement, uncertainty, source authority, evidence tier, and human decision authority. Do not invent compliance, exploitability, capacity, recovery, risk acceptance, whole-product security, release readiness, scheduling, deployment, or A100 conclusions. Return only strict JSON matching {slug}-role.schema.json. Authority boundary: {boundary}. Human review and semantic adjudication remain external.\nEND {designation} PROMPT\n").encode()
  atomic_write(ROOT/f"appendices/prompt-templates/candidates/{slug}/design-0.1.0.prompt.txt",prompt)
  atomic_write(ROOT/f"appendices/schemas/{slug}-role.schema.json",pretty_bytes(schema(designation,boundary)))
  atomic_write(ROOT/f"appendices/rubrics/{slug}-candidate-0.1.0.json",pretty_bytes({"rubric_id":f"RUBRIC-{designation}-CANDIDATE","version":"0.1.0","status":"candidate-comparison-only","authoritative_question":question,"required_controls":["exact_identity_focus_and_evidence_binding","domain_specific_question","evidence_tier_separation","no_effectiveness_without_test_or_runtime_evidence","preserve_identifiers_disagreement_and_unknowns","exact_locators","human_authority_and_downstream_ineligibility"]}))
  m=dict(MODEL);m.update({"purpose":f"GX-10 isolated {designation} comparison-only calibration","scope_designations":[designation]});atomic_write(ROOT/f"appendices/model-manifests/gx10-qwen3-32b-{slug}-calibration-0.1.0.json",pretty_bytes(m))
  atomic_write(ROOT/f"appendices/tool-manifests/{slug}-evidence-0.1.0.json",pretty_bytes({"toolchain_id":f"TOOLCHAIN-{designation}-EVIDENCE","version":"0.1.0","status":"candidate-comparison-only","designation":designation,"tools":[{"tool_id":"immutable-admitted-evidence-reader","access":"declared-read-only-evidence","mutating":False},{"tool_id":"evidence-locator","access":"admitted-evidence-only","mutating":False}],"network_access":"denied","runtime_access":"denied","secret_access":"denied","repository_mutation":"denied"}))
  manifest["prompts"][designation]={"path":f"appendices/prompt-templates/candidates/{slug}/design-0.1.0.prompt.txt","sha256":hashlib.sha256(prompt).hexdigest(),"source":f"agents/specialists/{load_json(ROOT/'agents/agent-identities.json')['agents'][next(i for i,x in enumerate(load_json(ROOT/'agents/agent-identities.json')['agents']) if x['designation']==designation)]['specification'].split('/')[-1]}","status":"candidate"}
  if designation in SEED:
   profile=load_json(ROOT/f"agents/focus-profiles/{slug}.json")
   atomic_write(ROOT/f"appendices/maturity-manifests/{slug}-bounded-calibration-0.1.0.json",pretty_bytes({"record_version":"0.1.0","designation":designation,"registry_status_preserved":"seed","scope":"bounded ADR-0039 candidate calibration only","checks":{"identity":"passed","source_specification":"passed","focus_profile":"passed","authoritative_question":"passed","prohibited_conclusions":"passed","strict_output_schema":"passed","evidence_and_authority_boundaries":"passed","rollback":"passed"},"focus_profile_hash":profile["source"]["specification_sha256"],"result":"sufficient_for_bounded_candidate_calibration","deployment_or_promotion_effect":False}))
 atomic_write(ROOT/"appendices/prompt-templates/candidates/manifest.json",pretty_bytes(manifest));print(json.dumps({"generated":len(ROLES),"seed_maturity_records":len(SEED)}));return 0
if __name__=="__main__":raise SystemExit(main())
