#!/usr/bin/env python3
"""Generate deterministic agent catalogs from the identity registry."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "agents" / "agent-identities.json"
OUTPUT = ROOT / "agents" / "generated"
LAYER_ORDER = ["specialist", "product", "capability", "enterprise", "work", "orchestration"]


def registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


def catalog_json(data: dict) -> dict:
    return {
        "catalog_version": data["registry_version"],
        "generated_from": "agents/agent-identities.json",
        "agents": sorted(data["agents"], key=lambda item: (LAYER_ORDER.index(item["layer"]), item["designation"])),
    }


def catalog_markdown(data: dict) -> str:
    lines = [
        "# Generated Agent Catalog",
        "",
        "Generated from [`agent-identities.json`](../agent-identities.json). Do not edit this file directly.",
        "",
    ]
    agents = catalog_json(data)["agents"]
    for layer in LAYER_ORDER:
        lines.extend([
            f"## {layer.title()}",
            "",
            "| Designation | Display name | Status | Contract | Specification |",
            "|---|---|---|---|---|",
        ])
        for agent in (item for item in agents if item["layer"] == layer):
            spec = "../" + agent["specification"]
            lines.append(
                f"| `{agent['designation']}` | {agent['display_name']} | `{agent['status']}` | `{agent['contract_version']}` | [role specification]({spec}) |"
            )
        lines.append("")
    return "\n".join(lines)


def summary_markdown(data: dict) -> str:
    agents = data["agents"]
    lines = [
        "# Generated Agent Layer Summary",
        "",
        "Generated from [`agent-identities.json`](../agent-identities.json). Do not edit this file directly.",
        "",
        "| Layer | Total | Baseline | Candidate | Seed | Planned |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for layer in LAYER_ORDER:
        counts = Counter(item["status"] for item in agents if item["layer"] == layer)
        total = sum(counts.values())
        lines.append(f"| {layer} | {total} | {counts['baseline']} | {counts['candidate']} | {counts['seed']} | {counts['planned']} |")
    lines.append("")
    return "\n".join(lines)


def outputs() -> list[tuple[Path, str]]:
    data = registry()
    return [
        (OUTPUT / "agent-catalog.json", json.dumps(catalog_json(data), indent=2, sort_keys=True) + "\n"),
        (OUTPUT / "agent-catalog.md", catalog_markdown(data)),
        (OUTPUT / "layer-summary.md", summary_markdown(data)),
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, rendered in outputs():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != rendered:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8", newline="\n")
    if stale:
        print("Stale generated agent catalogs:")
        for path in stale:
            print(f"- {path}")
        return 1
    print("Agent catalogs verified." if args.check else "Agent catalogs written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

