#!/usr/bin/env python3
"""Record the ADR-0037 project-owner accept-as-is semantic disposition."""
from __future__ import annotations
import copy,uuid
from pathlib import Path
from typing import Any
from artifact_ledger import ArtifactLedger,content_hash
from validate_vertical_slice import ROOT,ValidationFailure,assert_schema,load_json
RUN=ROOT/"fixtures/enterprise-strategy-admission/evidence/2026-08-02/adr0037/gx10-live-evaluation";REG=ROOT/"appendices/governance/decision-authorities-0.1.0.json";NS=uuid.UUID("37000000-0000-4000-8000-000000000001");DECIDED="2026-08-02T13:00:00Z";DERIVED="2026-08-02T13:01:00Z"
LIMITS=["categorical_human_authority_evidence_is_projected_to_numeric_1_0_without_an_explicit_manifest_mapping_rule","numeric_confidence_fields_lack_a_complete_declared_derivation_formula","observed_only_1_0_distribution_requires_context_to_avoid_being_read_as_objective_completeness","accepted_live_project_evaluation_uses_legacy_scope_id_ENTERPRISE_FIXTURE_001"]
def hashed(v:dict[str,Any],f:str):m=copy.deepcopy(v);m[f]=None;v[f]=content_hash(m);return v
def owner():
 r=load_json(REG);o=next(x for x in r["authorities"] if x["authority_role"]=="project-owner")
 if "finalize_governance_record" not in o["allowed_actions"] or "HUMAN-PROJECT-OWNER-001" not in o["human_subject_ids"]:raise ValidationFailure("project owner finalization authority absent")
def load_exact_review():
 packet=load_json(RUN/"semantic-review-packet.json");candidate=load_json(RUN/"ent-strat-model-candidate.artifact.json");raw=load_json(RUN/"raw-response.json")
 assert_schema(packet,"enterprise-strategy-semantic-review-packet.schema.json","ADR-0037 packet")
 material=copy.deepcopy(candidate);candidate_hash=material["integrity"]["output_hash"];material["integrity"]["output_hash"]=None
 if content_hash(material)!=candidate_hash or raw!=candidate["extensions"]["enterprise"]["role"] or content_hash({**packet,"packet_hash":None})!=packet["packet_hash"] or (packet["candidate"]["id"],packet["candidate"]["hash"])!=(candidate["artifact"]["artifact_id"],candidate_hash):raise ValidationFailure("ADR-0037 exact historical review binding mismatch")
 return packet,candidate
def build_disposition():
 p,c=load_exact_review();owner();v={"disposition_id":str(uuid.uuid5(NS,p["packet_id"]+":accept-as-is")),"packet_id":p["packet_id"],"packet_hash":p["packet_hash"],"candidate_id":c["artifact"]["artifact_id"],"candidate_hash":c["integrity"]["output_hash"],"decided_at":DECIDED,"decided_by":{"authority_role":"project-owner","authority_name":"thomasverburgt","subject_id":"HUMAN-PROJECT-OWNER-001"},"disposition":"accept_as_is_with_acknowledged_limitations","reviewed_dimensions":p["review_dimensions"],"semantic_judgment":{"statement":"Accept as is and continue.","strategy_posture":"insufficient_evidence","effect":"semantic_acceptance_despite_documented_nonblocking_limitations"},"acknowledged_limitations":LIMITS,"acknowledged_boundaries":{"single_capability_only":True,"no_enterprise_strategy_approval":True,"no_investment_or_portfolio_decision":True,"no_composite_or_threshold":True,"comparison_only":True},"decision_authority":"project_owner","effect":"semantic_acceptance_record_only","scheduling_authorized":False,"report_effect":"none","deployment_effect":"none","disposition_hash":"sha256:"+"0"*64};hashed(v,"disposition_hash");assert_schema(v,"enterprise-strategy-semantic-disposition.schema.json","ADR-0037 disposition");return v
def validate_disposition(v):
 p,c=load_exact_review();assert_schema(v,"enterprise-strategy-semantic-disposition.schema.json","ADR-0037 disposition")
 if (v["packet_id"],v["packet_hash"],v["candidate_id"],v["candidate_hash"])!=(p["packet_id"],p["packet_hash"],c["artifact"]["artifact_id"],c["integrity"]["output_hash"]) or content_hash({**v,"disposition_hash":None})!=v["disposition_hash"]:raise ValidationFailure("ADR-0037 disposition mismatch")
def build_finalization(d):
 validate_disposition(d);v={"finalization_id":str(uuid.uuid5(NS,d["disposition_id"]+":finalization")),"target_record_type":"enterprise_strategy_semantic_disposition","target_record_id":d["disposition_id"],"target_record_hash":d["disposition_hash"],"finalized_on":"2026-08-02","finalized_by":{"authority_role":"project-owner","authority_name":"thomasverburgt","subject_id":"HUMAN-PROJECT-OWNER-001"},"checks":{"source_binding":True,"authority_binding":True,"record_integrity":True,"scope_binding":True},"finalization_state":"finalized","decision_authority":"project_owner","effect":"record_only","finalization_hash":"sha256:"+"0"*64};hashed(v,"finalization_hash");assert_schema(v,"project-owner-finalization.schema.json","ADR-0037 finalization");return v
def derive_eligibility(d,f,revoked=False):
 validate_disposition(d);assert_schema(f,"project-owner-finalization.schema.json","ADR-0037 finalization");ok=not revoked and f["target_record_hash"]==d["disposition_hash"] and f["finalization_state"]=="finalized";v={"eligibility_id":str(uuid.uuid5(NS,d["disposition_id"]+(":revoked" if revoked else ":active"))),"candidate_id":d["candidate_id"],"candidate_hash":d["candidate_hash"],"packet_id":d["packet_id"],"packet_hash":d["packet_hash"],"disposition_id":d["disposition_id"],"disposition_hash":d["disposition_hash"],"finalization_id":f["finalization_id"],"finalization_hash":f["finalization_hash"],"derived_at":DERIVED,"state":"eligible_for_enterprise_synthesis_candidate_evaluation" if ok else "not_eligible","rollback_state":"active" if ok else "revoked","reason":"project_owner_accepted_as_is_with_acknowledged_limitations" if ok else "eligibility_revoked","limitations_carried_forward":LIMITS,"decision_authority":"derived_from_project_owner_finalization","effect":"enterprise_synthesis_evaluation_eligibility_only","ent_strat_scheduled":False,"ent_synth_scheduled":False,"report_effect":"none","deployment_effect":"none","record_hash":"sha256:"+"0"*64};hashed(v,"record_hash");assert_schema(v,"enterprise-strategy-semantic-eligibility.schema.json","ADR-0037 eligibility");return v
def build_records():d=build_disposition();f=build_finalization(d);return d,f,derive_eligibility(d,f)
def persist_records(root:Path,d,f,e):
 l=ArtifactLedger(root);return [l.persist_record(f"enterprise-strategy-dispositions/{d['disposition_id']}.json","enterprise-strategy-disposition",d["disposition_id"],d),l.persist_record(f"project-owner-finalizations/{f['finalization_id']}.json","project-owner-finalization",f["finalization_id"],f),l.persist_record(f"enterprise-strategy-eligibility/{e['eligibility_id']}.json","enterprise-strategy-eligibility",e["eligibility_id"],e)]
