#!/usr/bin/env python3
"""ADR-0024 deterministic ENT-SYNTH candidate projection and admission controls."""
from __future__ import annotations
import copy,uuid
from pathlib import Path
from typing import Any
from artifact_ledger import ArtifactLedger,content_hash
from enterprise_arch_runtime import build_candidate as build_arch
from enterprise_governance_runtime import build_candidate as build_gov
from enterprise_strategy_runtime import build_candidate as build_strat
from validate_vertical_slice import ROOT,ValidationFailure,assert_schema,load_json
BASELINE=ROOT/"appendices/example-workflows/vertical-risk-slice.workflow.json";REPORT=ROOT/"fixtures/vertical-risk-slice/evidence/governance-increment3-report-reconciliation-2026-07-31/reference-run/report-package.json";REPORT_MACHINE=ROOT/"orchestration/state-machines/report-governance.state-machine.json";NAMESPACE=uuid.UUID("24000000-0000-4000-8000-000000000000");CREATED_AT="2026-08-02T00:15:00Z"
def sid(*p:str)->str:return str(uuid.uuid5(NAMESPACE,"|".join(p)))
def rehash(a:dict[str,Any])->dict[str,Any]:a["integrity"]["output_hash"]=None;a["integrity"]["output_hash"]=content_hash(a);return a
def synthesis_inputs(live:bool=False)->tuple[dict[str,Any],list[dict[str,Any]],dict[str,Any]]:
 if live:
  gate=load_json(ROOT/"fixtures/vertical-risk-slice/evidence/canonical-cap-risk-2026-07-31/accepted-ent-evidence.artifact.json");sysrisk=load_json(ROOT/"fixtures/vertical-risk-slice/evidence/canonical-ent-sysrisk-2026-07-31/accepted-ent-sysrisk.artifact.json");arts=[sysrisk,build_arch(live=True),build_gov(live=True),build_strat(live=True)];tiers=["accepted_live","candidate_live_protocol_only","candidate_live_protocol_only","candidate_live_protocol_only"]
 else:
  gate=load_json(ROOT/"fixtures/vertical-risk-slice/gold/ent-evidence.artifact.json");arts=[load_json(ROOT/"fixtures/vertical-risk-slice/gold/ent-sysrisk.artifact.json"),build_arch(),build_gov(),build_strat()];tiers=["adjudicated_fixture"]*4
 inputs=[]
 for a,t in zip(arts,tiers):inputs.append({"artifact_id":a["artifact"]["artifact_id"],"content_hash":content_hash(a),"designation":a["identity"]["designation"],"schema_version":"1.0.0","freshness":"fresh","compatibility":"compatible","evidence_tier":t,"authority_owner":"human domain authority","permitted_use":"authoritative_domain_reference" if t=="accepted_live" else "comparison_only"})
 m={"manifest_id":sid("live" if live else "fixture","input-manifest"),"manifest_version":"1.0.0","created_at":CREATED_AT,"scope_id":"ENTERPRISE-FIXTURE-001","gate_artifact_id":gate["artifact"]["artifact_id"],"gate_artifact_hash":content_hash(gate),"inputs":inputs,"manifest_hash":None};m["manifest_hash"]=content_hash(m);validate_manifest(m,gate,arts);return gate,arts,m
def validate_manifest(m:dict[str,Any],gate:dict[str,Any],arts:list[dict[str,Any]])->None:
 assert_schema(m,"enterprise-synthesis-input-manifest.schema.json","synthesis input manifest");x=copy.deepcopy(m);h=x["manifest_hash"];x["manifest_hash"]=None
 if content_hash(x)!=h:raise ValidationFailure("synthesis input manifest hash mismatch")
 if (m["gate_artifact_id"],m["gate_artifact_hash"])!=(gate["artifact"]["artifact_id"],content_hash(gate)):raise ValidationFailure("synthesis gate binding mismatch")
 expected=[(a["artifact"]["artifact_id"],content_hash(a),a["identity"]["designation"]) for a in arts];actual=[(x["artifact_id"],x["content_hash"],x["designation"]) for x in m["inputs"]]
 if expected!=actual or len(actual)!=len(set(x[0] for x in actual)):raise ValidationFailure("synthesis exact artifact set mismatch")
 for x in m["inputs"]:
  if x["evidence_tier"]!="accepted_live" and x["permitted_use"]!="comparison_only":raise ValidationFailure("candidate or fixture synthesis input was promoted")
def role_template(gate:dict[str,Any],arts:list[dict[str,Any]],m:dict[str,Any],live:bool=False)->dict[str,Any]:
 snapshots=[];summaries=[];contrib=[]
 for a,i in zip(arts,m["inputs"]):
  role=a["extensions"]["enterprise"]["role"];rh=content_hash(role);snapshots.append({"artifact_id":i["artifact_id"],"designation":i["designation"],"source_role_hash":rh,"evidence_tier":i["evidence_tier"],"preserved":True});summaries.append({"designation":i["designation"],"artifact_id":i["artifact_id"],"summary":"Source domain posture retained without authority change.","evidence_tier":i["evidence_tier"],"source_role_hash":rh});contrib.append({"synthesis_assertion_id":f"SYNTH-{i['designation']}","statement":"Source domain posture is available at its declared evidence tier.","source_artifact_ids":[i["artifact_id"]],"source_role_hashes":[rh],"transformation":"direct_summary","uncertainty":"No cross-domain semantic conclusion is authorized by candidate evidence."})
 mixed=live;return {"designation":"ENT-SYNTH","evidence_tier":"accepted_and_candidate_mixed_tier_protocol_smoke" if live else "adjudicated_multi_domain_synthesis_fixture","fitness_claim":"mixed_tier_protocol_lineage_smoke_only" if live else "synthesis_contract_mechanics_only","manifest_binding":{"gate_artifact_id":m["gate_artifact_id"],"gate_artifact_hash":m["gate_artifact_hash"],"synthesis_manifest_id":m["manifest_id"],"synthesis_manifest_hash":content_hash(m),"domain_artifact_ids":[x["artifact_id"] for x in m["inputs"]],"domain_artifact_hashes":[x["content_hash"] for x in m["inputs"]],"binding_state":"exact"},"input_evidence_tiers":[{"artifact_id":x["artifact_id"],"designation":x["designation"],"evidence_tier":x["evidence_tier"],"permitted_use":x["permitted_use"]} for x in m["inputs"]],"source_assertion_snapshots":snapshots,"enterprise_posture_summary":{"state":"mixed_tier_incomplete_authoritative" if mixed else "fixture_comparison_only","advisory_only":True,"statement":"Inputs are summarized without promoting evidence tier or changing domain authority."},"domain_summaries":summaries,"contribution_map":contrib,"terminology_normalizations":[],"derived_correlations":[],"unresolved_disagreements":[],"completeness":{"expected_designations":["ENT-SYSRISK","ENT-ARCH","ENT-GOV","ENT-STRAT"],"received_designations":[x["designation"] for x in m["inputs"]],"complete_set":True,"authoritative_live_complete":False},"report_boundary":{"report_package_modified":False,"distribution_state_machine_modified":False,"publication_authorized":False,"decision_recording_authorized":False},"decision_requests":[],"unsupported_claims":[],"downstream_handoff":{"consumers":["REPORT-PACKAGER-CANDIDATE","ENT-PORTFOLIO-CANDIDATE"],"handoff_state":"comparison_only","scheduled":False},"decision_authority":"human"}
def build_candidate(model_role:dict[str,Any]|None=None,live:bool=False)->dict[str,Any]:
 gate,arts,m=synthesis_inputs(live);r=role_template(gate,arts,m,live);aid=sid("live" if live else "fixture","artifact");caps=sorted({c for a in arts for c in a["scope"].get("participating_capabilities",[])}) or ["ENTERPRISE-FIXTURE-001"]
 c={"identity":{"agent_uuid":"a4911647-648f-43fd-a51a-ed60d0d9bdf9","designation":"ENT-SYNTH","display_name":"Enterprise Synthesis Agent","agent_version":"design-0.1.0","contract_version":"1.0.0"},"artifact":{"artifact_id":aid,"artifact_type":"enterprise-synthesis-posture","created_at":CREATED_AT,"lifecycle_state":"complete","links":{"parents":[],"children":[gate["artifact"]["artifact_id"]]+[a["artifact"]["artifact_id"] for a in arts],"peers":[]}},"execution":{"execution_id":sid(aid,"execution"),"model":"qwen3-32b" if model_role is not None else "deterministic-reference-agent","prompt_version":"design-0.1.0","rubric_version":"0.1.0","toolchain_version":"0.1.0","settings":{"temperature":0}},"scope":{"enterprise_scope_id":"ENTERPRISE-FIXTURE-001","participating_capabilities":caps,"assessment_period":"2026-08-01","decision_context":"candidate_calibration"},"inputs":[{"artifact_id":gate["artifact"]["artifact_id"],"hash":content_hash(gate),"compatibility":"compatible","freshness":"fresh"}]+[{"artifact_id":a["artifact"]["artifact_id"],"hash":content_hash(a),"compatibility":"compatible","freshness":"fresh"} for a in arts]+[{"reference":"enterprise-synthesis-input-manifest","hash":content_hash(m),"compatibility":"compatible","freshness":"fresh"}],"methodology":{"method":"tier-preserving domain synthesis","limitations":["Candidate comparison only","Not a report or distribution decision"]},"coverage":{"eligible":4,"reviewed":4,"omitted":0,"inaccessible":0,"unknown":3 if live else 0,"negative_evidence":0},"observations":[],"assessments":[],"findings":[],"patterns":[],"insights":[],"conflicts":[],"confidence":{"evidence":0.7,"assessment":1.0,"review":1.0,"decision":None,"provenance":[{"source":"tiered synthesis manifest","version":"1.0.0"}]},"decisions_requested":[],"consumers":r["downstream_handoff"]["consumers"],"decision_authority":"human","integrity":{"input_hash":content_hash({"gate":content_hash(gate),"manifest":content_hash(m)}),"output_hash":None,"attestation_ref":None,"retention_class":"candidate-test","schema_validation":"passed"},"extensions":{"enterprise":{"enterprise_scope":{"enterprise_scope_id":"ENTERPRISE-FIXTURE-001","assessment_period":"2026-08-01"},"participating_capabilities":caps,"capability_input_manifest":m["inputs"],"cross_capability_correlations":r["derived_correlations"],"enterprise_assertions":r["contribution_map"],"systemic_dependencies":[],"enterprise_unknowns":[],"unresolved_disagreements":r["unresolved_disagreements"],"confidence_reconciliation":{"method":"preserve source confidence and tier","result":None},"human_decision_requests":[],"enterprise_traceability_manifest":r["manifest_binding"],"role":r}}};rehash(c);validate_candidate(c,gate,arts,m,live);return c
def validate_candidate(c:dict[str,Any],gate:dict[str,Any],arts:list[dict[str,Any]],m:dict[str,Any],live:bool=False)->None:
 validate_manifest(m,gate,arts);assert_schema(c,"universal-agent-artifact.schema.json","ENT-SYNTH candidate");e=c["extensions"]["enterprise"];assert_schema(e,"enterprise-extension.schema.json","ENT-SYNTH extension");r=e["role"];assert_schema(r,"ent-synth-role.schema.json","ENT-SYNTH role");x=copy.deepcopy(c);h=x["integrity"]["output_hash"];x["integrity"]["output_hash"]=None
 if content_hash(x)!=h or r!=role_template(gate,arts,m,live):raise ValidationFailure("ENT-SYNTH projection, provenance, tier, or authority mismatch")
 if any(n["designation"]=="ENT-SYNTH" for n in load_json(BASELINE)["nodes"]):raise ValidationFailure("ENT-SYNTH candidate cannot be baseline scheduled")
def persist_candidate(root:Path,c:dict[str,Any])->dict[str,Any]:return ArtifactLedger(root).persist_artifact(c)
