#!/usr/bin/env python3
"""Record the ADR-0038 project-owner ENT-SYNTH semantic acceptance."""
from __future__ import annotations
import copy, hashlib, json, uuid
from pathlib import Path
from typing import Any
from accepted_live_enterprise_synthesis_runtime import build_candidate
from artifact_ledger import ArtifactLedger, content_hash
from validate_vertical_slice import ROOT, ValidationFailure, assert_schema, load_json
RUN=ROOT/"fixtures/enterprise-synthesis-admission/evidence/2026-08-02/adr0038/gx10-live-evaluation/final-run"
REGISTRY=ROOT/"appendices/governance/decision-authorities-0.1.0.json"
NS=uuid.UUID("38000000-0000-4000-8000-000000000002");DECIDED="2026-08-02T18:00:00Z";DERIVED="2026-08-02T18:01:00Z"
BOUNDARIES=["bounded_four_domain_single_capability_evaluation_only","authoritative_live_complete_means_complete_only_within_declared_test_set","universal_confidence_1_0_is_projection_fidelity_not_enterprise_readiness","cross_domain_correlation_quality_not_demonstrated","comparison_only_no_report_distribution_scheduling_deployment_or_production_authority"]
def hashed(v:dict[str,Any],f:str):m=copy.deepcopy(v);m[f]=None;v[f]=content_hash(m);return v
def authority(action:str):
 r=load_json(REGISTRY);assert_schema(r,"decision-authority-registry.schema.json","authority registry");o=next(x for x in r["authorities"] if x["authority_role"]=="project-owner")
 if r["registry_version"]!="0.10.0" or action not in o["allowed_actions"] or "HUMAN-PROJECT-OWNER-001" not in o["human_subject_ids"] or "CODE-HARNESS-PROJECT-001" not in o["scope_ids"]:raise ValidationFailure("project-owner ENT-SYNTH authority absent")
def load_exact_review():
 p=load_json(RUN/"semantic-review-packet.json");c=load_json(RUN/"ent-synth-model-candidate.artifact.json");raw_bytes=(RUN/"raw-response.json").read_bytes();raw=json.loads(raw_bytes);raw_hash=hashlib.sha256(raw_bytes).hexdigest();assert_schema(p,"enterprise-synthesis-semantic-review-packet.schema.json","ADR-0038 packet")
 if content_hash({**p,"packet_hash":None})!=p["packet_hash"] or raw!=c["extensions"]["enterprise"]["role"] or build_candidate(raw_hash)!=c or (p["candidate"]["id"],p["candidate"]["hash"])!=(c["artifact"]["artifact_id"],c["integrity"]["output_hash"]):raise ValidationFailure("ADR-0038 exact review binding mismatch")
 return p,c
def build_disposition():
 p,c=load_exact_review();authority("accept_enterprise_synthesis_semantics");v={"disposition_id":str(uuid.uuid5(NS,p["packet_id"]+":accepted")),"packet_id":p["packet_id"],"packet_hash":p["packet_hash"],"candidate_id":c["artifact"]["artifact_id"],"candidate_hash":c["integrity"]["output_hash"],"decided_at":DECIDED,"decided_by":{"authority_role":"project-owner","authority_name":"thomasverburgt","subject_id":"HUMAN-PROJECT-OWNER-001"},"disposition":"accept_semantically_faithful_for_bounded_integration_evaluation","reviewed_dimensions":p["review_dimensions"],"semantic_judgment":{"statement":"Approve final ENT-SYNTH candidate as semantically faithful.","posture":"bounded_domain_set_preserved_human_review_required","effect":"semantic_acceptance_for_later_bounded_integration_evaluation_only"},"acknowledged_boundaries":BOUNDARIES,"decision_authority":"project_owner","effect":"semantic_acceptance_record_only","scheduling_authorized":False,"report_effect":"none","deployment_effect":"none","disposition_hash":"sha256:"+"0"*64};hashed(v,"disposition_hash");assert_schema(v,"enterprise-synthesis-semantic-disposition.schema.json","ADR-0038 disposition");return v
def validate_disposition(v):
 p,c=load_exact_review();assert_schema(v,"enterprise-synthesis-semantic-disposition.schema.json","ADR-0038 disposition");authority("accept_enterprise_synthesis_semantics")
 if (v["packet_id"],v["packet_hash"],v["candidate_id"],v["candidate_hash"])!=(p["packet_id"],p["packet_hash"],c["artifact"]["artifact_id"],c["integrity"]["output_hash"]) or content_hash({**v,"disposition_hash":None})!=v["disposition_hash"]:raise ValidationFailure("ADR-0038 disposition mismatch")
def build_finalization(d):
 validate_disposition(d);authority("finalize_governance_record");v={"finalization_id":str(uuid.uuid5(NS,d["disposition_id"]+":finalization")),"target_record_type":"enterprise_synthesis_semantic_disposition","target_record_id":d["disposition_id"],"target_record_hash":d["disposition_hash"],"finalized_on":"2026-08-02","finalized_by":{"authority_role":"project-owner","authority_name":"thomasverburgt","subject_id":"HUMAN-PROJECT-OWNER-001"},"checks":{"source_binding":True,"authority_binding":True,"record_integrity":True,"scope_binding":True},"finalization_state":"finalized","decision_authority":"project_owner","effect":"record_only","finalization_hash":"sha256:"+"0"*64};hashed(v,"finalization_hash");assert_schema(v,"project-owner-finalization.schema.json","ADR-0038 finalization");return v
def derive_eligibility(d,f,revoked=False):
 validate_disposition(d);assert_schema(f,"project-owner-finalization.schema.json","ADR-0038 finalization");active=not revoked and f["target_record_id"]==d["disposition_id"] and f["target_record_hash"]==d["disposition_hash"] and f["finalization_state"]=="finalized" and all(f["checks"].values());v={"eligibility_id":str(uuid.uuid5(NS,d["disposition_id"]+(":revoked" if revoked else ":active"))),"candidate_id":d["candidate_id"],"candidate_hash":d["candidate_hash"],"packet_id":d["packet_id"],"packet_hash":d["packet_hash"],"disposition_id":d["disposition_id"],"disposition_hash":d["disposition_hash"],"finalization_id":f["finalization_id"],"finalization_hash":f["finalization_hash"],"derived_at":DERIVED,"state":"eligible_for_enterprise_shadow_integration_evaluation" if active else "not_eligible","rollback_state":"active" if active else "revoked","reason":"project_owner_accepted_semantically_faithful_for_bounded_integration_evaluation" if active else "eligibility_revoked","boundaries_carried_forward":BOUNDARIES,"decision_authority":"derived_from_project_owner_finalization","effect":"enterprise_shadow_integration_evaluation_eligibility_only","ent_synth_scheduled":False,"report_effect":"none","deployment_effect":"none","record_hash":"sha256:"+"0"*64};hashed(v,"record_hash");assert_schema(v,"enterprise-synthesis-semantic-eligibility.schema.json","ADR-0038 eligibility");return v
def build_records():d=build_disposition();f=build_finalization(d);return d,f,derive_eligibility(d,f)
def persist_records(root:Path,d,f,e):
 l=ArtifactLedger(root);return [l.persist_record(f"enterprise-synthesis-dispositions/{d['disposition_id']}.json","enterprise-synthesis-disposition",d["disposition_id"],d),l.persist_record(f"project-owner-finalizations/{f['finalization_id']}.json","project-owner-finalization",f["finalization_id"],f),l.persist_record(f"enterprise-synthesis-eligibility/{e['eligibility_id']}.json","enterprise-synthesis-eligibility",e["eligibility_id"],e)]
