#!/usr/bin/env python3
"""Build deterministic ADR-0039 Increment 5-7 candidates; human review stays deferred."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import run_specialist_build_supply_chain_increment2 as base
from specialist_shadow_calibration_runtime import ROOT, seal_hash, validate_manifest

DEFAULT_OUTPUT = ROOT / "fixtures" / "specialist-increment567" / "gold"
UDS_URI = "https://github.com/defenseunicorns/uds-core.git"
UDS_REV = "329ade01852f9e570d31cb7b19d9979152938c17"
HARNESS_URI = "https://github.com/thomasverburgt/Code-Review-Harness.git"
# Content-addressed retained-candidate bundle identity (not a branch or deployment revision).
HARNESS_REV = "16a7129e9e19969bce5528b046b2fc94ef5af60b"

# Evidence tuples are ID, path, line, exact safe excerpt, section, full-file hash, source type.
CONFIG = {
    "SPEC-ARCH": {"slug":"spec-arch","display":"Architecture Reviewer","domain":"architecture","increment":5,"tier":"design_model","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-ARCH-PEPR-001","docs/.c4/model.c4",20,"        description 'Namespace containing Pepr controller and admission pods for policy enforcement and automated integration. Pepr is a Kubernetes controller built with TypeScript that implements UDS Core security policies and automates integration with the rest of the platform via custom resources.'","Pepr system namespace","sha256:1eb30203768d03f22c9ac0c9e6a4df76bd4d38696a5187b5333cb7d82fc64e8a","git_source")],
      "observation":"The admitted C4 model declares a Pepr policy and integration namespace inside the UDS Core cluster boundary.","finding":"The design record communicates intended structure but does not demonstrate implemented or observed conformance.","corrective":"Retain implementation mappings and observed deployment evidence linked to the design elements.","preventive":"Continuously reconcile intended, implemented, and observed architecture states without collapsing them.","unknown":"Implementation conformance, runtime topology, ownership, drift, and architectural fitness remain unknown.","missing":["implementation mapping","observed runtime topology","architecture conformance record"]},
    "SPEC-INTEROP": {"slug":"spec-interop","display":"Interoperability and Integration Reviewer","domain":"interface_compatibility","increment":5,"tier":"source_contract","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-INTEROP-UDP-001","src/pepr/operator/crd/sources/package/v1alpha1.ts",185,"          \"The routing protocol for this expose entry. When set to `UDP`, the entry routes through Envoy Gateway instead of Istio. Hostname routing fields (`host`, `domain`, `advancedHTTP`, `match`) are invalid for UDP entries. UDP traffic is not protected by Istio AuthorizationPolicy or mTLS.\",","Expose protocol contract","sha256:f4ba8a9ea016ce84b42843eca7bcc0d501c5ee7734387f9fd7adba781a06dbd4","git_source")],
      "observation":"The admitted source contract distinguishes UDP routing, incompatible hostname fields, and its trust-control boundary.","finding":"A declared interface contract does not demonstrate producer-consumer compatibility, version negotiation, or live integration behavior.","corrective":"Retain versioned producer and consumer contracts plus compatibility and failure-path tests.","preventive":"Gate interface changes on contract compatibility, negotiated-version, and negative integration evidence.","unknown":"Consumer population, version compatibility, error semantics, and runtime integration remain unknown.","missing":["consumer contracts","compatibility tests","runtime integration traces"]},
    "SPEC-DATA": {"slug":"spec-data","display":"Data Architecture and Information Management Reviewer","domain":"data_architecture","increment":5,"tier":"configuration","state":"insufficient_evidence","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-DATA-BACKUP-001","src/velero/values/values.yaml",28,"  backupStorageLocation:","Velero backup storage configuration","sha256:2389e0a2df571bd8113795f271fe8dd1fd0e76ff82fc830536696a0580b4aef6","configuration")],
      "observation":"The admitted Velero configuration declares a backup-storage location section.","finding":"The configuration does not identify data ownership, classification, lineage, retention, recovery objectives, or successful restore evidence.","corrective":"Retain a data inventory, ownership and lineage records, retention rules, recovery objectives, and restore-test results.","preventive":"Bind data stores to named owners, classifications, lifecycle policies, and tested recovery evidence.","unknown":"Data population, semantics, lineage, retention, access, loss tolerance, and recovery effectiveness remain unknown.","missing":["data inventory and ownership","lineage and retention records","restore test results"]},
    "SPEC-DIAGRAM": {"slug":"spec-diagram","display":"Diagram and Design-Model Reviewer","domain":"design_model_consistency","increment":5,"tier":"design_model","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-DIAGRAM-PURPOSE-001","docs/.c4/README.md",7,"In UDS Core, we use C4 diagrams to visualize and document our system architecture, including namespaces, components, and their relationships. This helps developers understand how different parts of the system interact with each other.","C4 model purpose","sha256:38344c44031dc5f7f366ac96057a939dc715dd85b1c957b41c24c74152f46aa7","git_source")],
      "observation":"The repository states that its C4 model represents namespaces, components, relationships, and interactions.","finding":"The design-model purpose is declared, but completeness, freshness, consistency, and implementation conformance are not demonstrated.","corrective":"Retain generated diagram outputs, model validation, freshness checks, and implementation mappings.","preventive":"Validate diagram syntax, identifiers, relationships, and drift as a distinct documentation control.","unknown":"Model completeness, renderability, freshness, and implementation correspondence remain unknown; absence or drift alone is not an implementation defect.","missing":["rendered model validation","freshness evidence","implementation mapping"]},
    "SPEC-IO": {"slug":"spec-io","display":"I/O and Resource Interaction Reviewer","domain":"resource_interactions","increment":5,"tier":"configuration","state":"bounded_concern","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-IO-EGRESS-001","src/test/app-admin-package.yaml",47,"        remoteGenerated: Anywhere","httpbin egress destination","sha256:813beed77a5a843c83869037cc21c957c22b074db3a6a380816438d86e91813a","configuration")],
      "observation":"The admitted package configuration declares an Anywhere-generated egress destination for the selected workload.","finding":"The declaration identifies a broad intended interaction but does not demonstrate rendered policy, actual endpoints, data exchanged, authorization, or runtime use.","corrective":"Retain rendered resource policy and observed, identity-bound interaction evidence for each endpoint and data class.","preventive":"Inventory external interactions and continuously reconcile declared destinations, permissions, data, and observed use.","unknown":"Actual endpoints, protocols, data flows, permissions, runtime use, and blast radius remain unknown.","missing":["rendered policy","endpoint and data inventory","runtime interaction evidence"]},
    "SPEC-OBS": {"slug":"spec-obs","display":"Observability Reviewer","domain":"observability","increment":6,"tier":"configuration","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-OBS-RULE-001","src/vector/chart/templates/uptime-recording-rules.yaml",14,"        - record: uds:vector:up","Vector uptime recording rule","sha256:4fa8de051bd3d6b0f2b043b20e8c451beddee1f25836fed990c7765ee49d2942","configuration")],
      "observation":"The admitted chart configures a Vector uptime recording rule.","finding":"A recording-rule definition does not demonstrate scrape health, alert coverage, diagnostic usefulness, ownership, or response effectiveness.","corrective":"Retain rule evaluation, alert routing, runbook, incident, and diagnosis evidence for the exact deployment.","preventive":"Map objectives and failure modes to tested signals, alerts, ownership, and diagnostic paths.","unknown":"Signal availability, alert effectiveness, diagnostic coverage, ownership, and operational response remain unknown.","missing":["rule evaluation results","alert and runbook evidence","incident diagnosis evidence"]},
    "SPEC-PERF": {"slug":"spec-perf","display":"Performance and Scalability Reviewer","domain":"performance_scalability","increment":6,"tier":"configuration","state":"bounded_concern","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-PERF-AUTOSCALE-001","src/grafana/values/values.yaml",96,"  enabled: false","Grafana autoscaling","sha256:7697509de4a2f6dc27c7d157afe8468e4a54050664c2f9ac23f4da094edfa871","configuration")],
      "observation":"The admitted Grafana values disable autoscaling in this configuration.","finding":"The static setting does not establish workload shape, objectives, capacity, saturation, latency, throughput, or scaling behavior.","corrective":"Retain workload definitions and repeatable measurements across relevant resource and failure conditions.","preventive":"Bind performance conclusions to versioned workloads, environments, objectives, distributions, and reproducible results.","unknown":"Capacity, latency, throughput, scaling limits, bottlenecks, and A100 behavior remain unknown; GX-10 results cannot establish A100 performance.","missing":["workload model","performance objectives","repeatable runtime measurements"]},
    "SPEC-FMECA": {"slug":"spec-fmeca","display":"Reliability, Resilience, and FMECA Reviewer","domain":"reliability_resilience","increment":6,"tier":"source_contract","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-FMECA-BACKOFF-001","src/pepr/operator/reconcilers/package-reconciler.ts",68,"    const backOffSeconds = 3 ** pkg.status.retryAttempt;","package reconciliation backoff","sha256:cd53d7cea37267fd9a12d3ae2d9a868e64a0d4c415a9802f9391f7de6a1c3b82","git_source")],
      "observation":"The admitted reconciler source calculates exponential retry backoff from the retry-attempt count.","finding":"A retry mechanism is visible in source, but failure modes, propagation, retry bounds, recovery effectiveness, and mission effects are not demonstrated.","corrective":"Retain failure-mode analysis, bounded retry tests, fault injection, recovery measurements, and mission-effect mappings.","preventive":"Connect each critical failure mode to detection, control, bounded recovery, verification, and residual-risk ownership.","unknown":"Failure likelihood, propagation, retry exhaustion, recovery time, control effectiveness, and mission effect remain unknown.","missing":["failure-mode inventory","fault-injection results","recovery and mission-effect evidence"]},
    "SPEC-RESEARCH": {"slug":"spec-research","display":"Research and Product-Store Agent","domain":"research_provenance","increment":7,"tier":"external_source","state":"observed_positive_control","repository_uri":UDS_URI,"revision":UDS_REV,
      "evidence":[("EVIDENCE-RESEARCH-LICENSE-001","LICENSE.md",1,"                    GNU AFFERO GENERAL PUBLIC LICENSE","repository license","sha256:6f1e622c82a380075843bb084a7ec3b1f1d12a4a02526d75e78b0924a860aa75","external_record")],
      "observation":"The admitted immutable repository includes an attributable AGPL license record.","finding":"License and revision establish bounded provenance, but source authority, claim-specific relevance, currentness, and corroboration still require explicit evaluation.","corrective":"Retain claim-to-source mappings with author, license, retrieval time, revision, currency rationale, and corroboration.","preventive":"Admit external research only through content-addressed, licensed, attributable, claim-scoped source records.","unknown":"Claim-specific authority, bias, currentness, completeness, and corroboration remain unknown; no network research was performed.","missing":["claim-specific source mapping","currency rationale","independent corroboration"]},
    "SPEC-RISK": {"slug":"spec-risk","display":"Product Risk Reviewer","domain":"product_risk","increment":7,"tier":"retained_candidate","state":"insufficient_evidence","repository_uri":HARNESS_URI,"revision":HARNESS_REV,
      "evidence":[("EVIDENCE-RISK-COMMS-001","fixtures/specialist-k8s-secure-increment34/gold/spec-comms/candidate.artifact.json",159,"\"statement\": \"Effective identity, encryption, authorization, exposure, lateral-movement resistance, and failure behavior are not demonstrated without runtime traffic evidence.\",","retained SPEC-COMMS unknown","sha256:9258179259df5fe9a582250d59b16530438db422cb3bbbf12befe820c9f0c9e7","external_record"),("EVIDENCE-RISK-PLATFORM-001","fixtures/specialist-k8s-secure-increment34/gold/spec-k8s-platform/candidate.artifact.json",153,"\"statement\": \"Actual installation, enforcement, coverage, tenant isolation, drift, and platform effectiveness remain unknown from IaC desired state alone.\",","retained SPEC-K8S-PLATFORM unknown","sha256:6e111eb3b04235b9804f506117e512d293c961e45ba8d7d328d6c9b4e25f55fd","external_record")],
      "observation":"Two retained child candidates preserve distinct communication and platform unknowns.","finding":"The child records support evidence gaps, not quantified likelihood, consequence, aggregate risk, risk acceptance, or whole-product disposition.","corrective":"Add explicit cause-event-consequence records, likelihood and impact bases, control evidence, uncertainty, and named decision authority.","preventive":"Preserve child identifiers and disagreements; require human authority for risk acceptance and prioritization.","unknown":"Risk events, likelihood, consequence, control effectiveness, aggregation logic, tolerance, and acceptance remain unknown.","missing":["cause-event-consequence records","likelihood and consequence evidence","risk authority disposition"]},
    "SPEC-SECURITY": {"slug":"spec-security","display":"Security Posture Reviewer","domain":"integrated_security_posture","increment":7,"tier":"retained_candidate","state":"insufficient_evidence","repository_uri":HARNESS_URI,"revision":HARNESS_REV,
      "evidence":[("EVIDENCE-SECURITY-CODE-001","fixtures/specialist-k8s-secure-increment34/gold/spec-secure-code/candidate.artifact.json",155,"\"statement\": \"Population coverage, generated-code boundaries, bypass behavior, execution-path reachability, and exploitability remain unknown.\",","retained SPEC-SECURE-CODE unknown","sha256:ee37ef0ec6f3603d92452c93166502f17e5b4bdbce95d316ee6febffa7cb2145","external_record"),("EVIDENCE-SECURITY-SECRETS-001","fixtures/specialist-k8s-secure-increment34/gold/spec-secrets/candidate.artifact.json",153,"\"statement\": \"Secret classification, validity, ownership, age, storage policy, and blast radius remain unknown; no raw value is admitted.\",","retained SPEC-SECRETS unknown","sha256:adfc0c63a03238dd7bf01dcc797545977a800d760ac45f92cf744face4021bb5","external_record"),("EVIDENCE-SECURITY-COMMS-001","fixtures/specialist-k8s-secure-increment34/gold/spec-comms/candidate.artifact.json",159,"\"statement\": \"Effective identity, encryption, authorization, exposure, lateral-movement resistance, and failure behavior are not demonstrated without runtime traffic evidence.\",","retained SPEC-COMMS unknown","sha256:9258179259df5fe9a582250d59b16530438db422cb3bbbf12befe820c9f0c9e7","external_record")],
      "observation":"Retained secure-code, secrets, and communications candidates preserve separate unknowns and evidence provenance.","finding":"The admitted children do not justify a whole-product security conclusion, release decision, or risk acceptance.","corrective":"Retain domain-complete evidence, conflicts, coverage, control effectiveness, and qualified human adjudication before posture synthesis.","preventive":"Preserve child claims and disagreement; prohibit security synthesis from exceeding admitted evidence or human authority.","unknown":"Whole-product coverage, exploitability, exposure, control effectiveness, residual risk, and release readiness remain unknown.","missing":["domain-complete evidence","control-effectiveness evidence","qualified semantic adjudication"]},
}

AUTHORITY = {
 "SPEC-ARCH":"architecture_assessment_only_no_product_or_release_approval","SPEC-INTEROP":"interface_assessment_only_no_product_or_release_approval","SPEC-DATA":"data_assessment_only_no_governance_or_product_approval","SPEC-DIAGRAM":"design_model_assessment_only_no_implementation_or_product_approval","SPEC-IO":"resource_interaction_assessment_only_no_runtime_or_product_approval","SPEC-OBS":"observability_assessment_only_no_operational_or_product_approval","SPEC-PERF":"performance_assessment_only_no_capacity_or_product_approval","SPEC-FMECA":"reliability_assessment_only_no_resilience_or_product_approval","SPEC-RESEARCH":"research_evidence_only_no_authority_or_product_approval","SPEC-RISK":"risk_characterization_only_no_acceptance_or_product_approval","SPEC-SECURITY":"security_synthesis_only_no_whole_product_release_or_acceptance"
}

def role_payload(designation: str, refs: list[str]) -> dict[str, Any]:
    cfg = CONFIG[designation]
    return {"designation": designation, "domain_records": [{"record_id": f"RECORD-{designation.removeprefix('SPEC-')}-{i+1:03d}", "subject": evidence[4], "assessment_state": cfg["state"], "evidence_tier": cfg["tier"], "effectiveness": "configured_not_demonstrated" if cfg["tier"] in {"configuration","source_contract"} else "not_assessed", "evidence_refs": [evidence[0]]} for i,evidence in enumerate(cfg["evidence"])], "coverage": {"records_reviewed": len(refs), "tests_reviewed": 0, "runtime_records_reviewed": 0, "external_sources_reviewed": 1 if designation == "SPEC-RESEARCH" else 0}, "unknowns": [{"unknown_id": f"UNKNOWN-{designation.removeprefix('SPEC-')}-001", "statement": cfg["unknown"], "missing_evidence": cfg["missing"], "evidence_refs": refs}], "authority_boundary": AUTHORITY[designation]}

_original_build_manifest = base.build_manifest
_original_locator = base.locator

def _select(designation: str) -> None:
    cfg = CONFIG[designation]
    base.REPOSITORY_URI, base.REVISION = cfg["repository_uri"], cfg["revision"]
    base.INCREMENT_KEY = f"increment-{cfg['increment']}"
    base.INCREMENT_LABEL = f"Increment {cfg['increment']}"
    base.ENVIRONMENT_POLICY_VERSION = f"increment-{cfg['increment']}.0.0"
    base.LOCATOR_COLLECTOR = f"increment-{cfg['increment']}-deterministic-reference"

def build_manifest(designation: str) -> dict[str, Any]:
    _select(designation)
    value = _original_build_manifest(designation)
    value = seal_hash(value, "manifest_hash")
    validate_manifest(value)
    return value

def locator(evidence):
    return _original_locator(evidence)

def configure() -> None:
    base.CONFIG, base.role_payload = CONFIG, role_payload
    base.build_manifest, base.locator = build_manifest, locator
    base.CREATED_AT, base.GENERATED_AT = "2026-08-03T23:00:00Z", "2026-08-03T23:05:00Z"
    base.INCREMENT_SUMMARY = [5, 6, 7]

def main() -> int:
    configure()
    parser=argparse.ArgumentParser(description=__doc__); parser.add_argument("--output",type=Path,default=DEFAULT_OUTPUT); args=parser.parse_args()
    summary=base.generate(args.output.resolve()); summary.update({"suite":"adr0039-increment567-specialists","source_repository":"multiple_content_addressed_sources","source_revisions":[UDS_REV,HARNESS_REV],"human_review_deferred":True})
    base.atomic_write(args.output.resolve()/"summary.json",base.pretty_bytes(summary)); print(json.dumps(summary,indent=2,sort_keys=True)); return 0
if __name__ == "__main__": raise SystemExit(main())
